# Generated by Django 5.1.5 on 2025-04-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
